
package myrepo.server.repository;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskRepositoryService", targetNamespace = "http://repository.server.myrepo/", wsdlLocation = "http://localhost:8080/Repository/TaskRepositoryService?wsdl")
public class TaskRepositoryService
    extends Service
{

    private final static URL TASKREPOSITORYSERVICE_WSDL_LOCATION;
    private final static WebServiceException TASKREPOSITORYSERVICE_EXCEPTION;
    private final static QName TASKREPOSITORYSERVICE_QNAME = new QName("http://repository.server.myrepo/", "TaskRepositoryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Repository/TaskRepositoryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKREPOSITORYSERVICE_WSDL_LOCATION = url;
        TASKREPOSITORYSERVICE_EXCEPTION = e;
    }

    public TaskRepositoryService() {
        super(__getWsdlLocation(), TASKREPOSITORYSERVICE_QNAME);
    }

    public TaskRepositoryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKREPOSITORYSERVICE_QNAME, features);
    }

    public TaskRepositoryService(URL wsdlLocation) {
        super(wsdlLocation, TASKREPOSITORYSERVICE_QNAME);
    }

    public TaskRepositoryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKREPOSITORYSERVICE_QNAME, features);
    }

    public TaskRepositoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskRepositoryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaskRepository
     */
    @WebEndpoint(name = "TaskRepositoryPort")
    public TaskRepository getTaskRepositoryPort() {
        return super.getPort(new QName("http://repository.server.myrepo/", "TaskRepositoryPort"), TaskRepository.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskRepository
     */
    @WebEndpoint(name = "TaskRepositoryPort")
    public TaskRepository getTaskRepositoryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://repository.server.myrepo/", "TaskRepositoryPort"), TaskRepository.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKREPOSITORYSERVICE_EXCEPTION!= null) {
            throw TASKREPOSITORYSERVICE_EXCEPTION;
        }
        return TASKREPOSITORYSERVICE_WSDL_LOCATION;
    }

}
