
package myrepo.server.repository;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaskRepository", targetNamespace = "http://repository.server.myrepo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaskRepository {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "pairIn", targetNamespace = "http://repository.server.myrepo/", className = "myrepo.server.repository.PairIn")
    @ResponseWrapper(localName = "pairInResponse", targetNamespace = "http://repository.server.myrepo/", className = "myrepo.server.repository.PairInResponse")
    @Action(input = "http://repository.server.myrepo/TaskRepository/pairInRequest", output = "http://repository.server.myrepo/TaskRepository/pairInResponse")
    public void pairIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Double> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Double>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pairOut", targetNamespace = "http://repository.server.myrepo/", className = "myrepo.server.repository.PairOut")
    @ResponseWrapper(localName = "pairOutResponse", targetNamespace = "http://repository.server.myrepo/", className = "myrepo.server.repository.PairOutResponse")
    @Action(input = "http://repository.server.myrepo/TaskRepository/pairOutRequest", output = "http://repository.server.myrepo/TaskRepository/pairOutResponse")
    public List<Double> pairOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Double>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readPair", targetNamespace = "http://repository.server.myrepo/", className = "myrepo.server.repository.ReadPair")
    @ResponseWrapper(localName = "readPairResponse", targetNamespace = "http://repository.server.myrepo/", className = "myrepo.server.repository.ReadPairResponse")
    @Action(input = "http://repository.server.myrepo/TaskRepository/readPairRequest", output = "http://repository.server.myrepo/TaskRepository/readPairResponse")
    public List<Double> readPair(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
